- name: Set variables
  set_fact:
    venv_dir: "{{ src }}-venv"
    k8s_component_name: kubesphere

- name: Create directories
  file:
    path: "{{ k8s_dir }}/{{ k8s_cluster_name }}/{{ item }}"
    state: directory
  loop:
    - bin
    - playbooks
    - playbooks/files
    - playbooks/templates

- name: Create config files from templates
  template:
    force: "{{ (k8s_config_force_update | bool) or (k8s_all_force_update | bool) }}"
    src: "{{ k8s_component_name }}/{{ item }}.j2"
    dest: "{{ this_file_path }}"
    mode: u+rw
  vars:
    this_file_path: "{{ k8s_dir }}/{{ k8s_cluster_name }}/{{ item }}"
  loop:
    - "ansible.cfg"

- name: Copy component specific shell script files
  copy:
    force: yes
    src: "{{ k8s_component_name }}/{{ item }}"
    dest: "{{ this_file_path }}"
    mode: u+rwx
  vars:
    this_file_path: "{{ k8s_dir }}/{{ k8s_cluster_name }}/bin/{{ item }}"
  loop:
    - "deploy-cluster.sh"
    - "reset-cluster.sh"
    - "fetch-client.sh"

- name: Copy component specific playbook files
  copy:
    force: yes
    src: "{{ k8s_component_name }}/playbooks/{{ item }}"
    dest: "{{ this_file_path }}"
    mode: u+rw
  vars:
    this_file_path: "{{ k8s_dir }}/{{ k8s_cluster_name }}/playbooks/{{ item }}"
  loop:
    - "deploy-cluster.yml"
    - "reset-cluster.yml"
    - "fetch-client.yml"
    - "files/download-kubekey.sh"
